server:
  port: 8081

jwt:
  secret: "0123456789abcdef0123456789abcdef0123456789abcdef01"

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ayubo_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Indiwari@2002}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
