server:
  port: 8081

jwt:
  secret: "0123456789abcdef0123456789abcdef0123456789abcdef01"

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ayubo_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Indiwari@2002
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect




# Explicit JDBC properties to help Hibernate determine Dialect at startup
jakarta.persistence.jdbc.url: jdbc:mysql://localhost:3306/ayubo_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
jakarta.persistence.jdbc.user: root
jakarta.persistence.jdbc.password: Indiwari@2002
