spring.application.name=payment-service

# Run the Payment Service on port 8082
server.port=8088

# Your Stripe Secret Key
stripe.api.key=${STRIPE_API_KEY}
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ayubo_payments?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update