spring.application.name=appointment-service

# Database configuration (local development)
spring.datasource.url=jdbc:mysql://localhost:3306/ayubo_appointment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Indiwari@2002

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Reduce noisy logging
logging.level.org.hibernate.SQL=warn

# Fallback dialect for environments where JDBC metadata isn't available
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
