server:
  port: 8082

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://localhost:3307/appointment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Himasha@2002

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  notification:
    base-url: http://localhost:8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html